[package]
name = "PDBDescriptors"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.9.0"
rand = "0.9.0"
clap = {version = "4.4", features = ["derive"] }
pdb-io = { path = "../pdb-io" }
metrics = { path = "../metrics" }