[package]
name = "PDBDescriptors"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.9.0"
rand = "0.9.0"
clap = {version = "4.4", features = ["derive"] }
pdb_io = { path = "../pdb_io" }
metrics = { path = "../metrics" }
sasa = {path = "../sasa" }